from pathlib import Path
import json
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,Image,PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
P=Path(__file__).resolve().parent;rr=[json.loads(p.read_text()) for p in sorted((P/'results').glob('*.json'))];single=next(x for x in rr if x['layout']=='single-161');two=next(x for x in rr if x['layout']=='two-equal');s=getSampleStyleSheet();s['BodyText'].fontSize=9;s['BodyText'].leading=13;story=[]
def p(x):story.extend([Paragraph(x,s['BodyText']),Spacer(1,9)])
def h(x):story.append(Paragraph(x,s['Heading1']))
def table(rows,widths):
 t=Table([[Paragraph(str(c),s['BodyText']) for c in row] for row in rows],colWidths=widths,repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e4edf1')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]));story.append(t)
h('B2 position and removal of B3')
p('<b>Preferred study arrangement: remove B3 and move B2 to y = 161.375 inches</b> north of the south garage wall: 13 ft 5-3/8 in. This is 23-5/8 inches south of its previous y = 185-inch location. Use the full T-N lower chord as the north floor support. The resulting two joist spans are each 91.625 inches (7 ft 7-5/8 in).')
p('B3 was a floor-level beam in the previous model. Removing it is not deletion of the floor support: its job is transferred to the T-N truss lower chord through joist seats/connections that still need detailing. This comparison gives no new load credit to the existing north garage wall.')
table([['','One B2','Two beams'],['Positions north of south wall','161.375 in','130.833 and 191.917 in'],['Candidate interior rails','W8×31','W8×24 each'],['Longest joist span','91.625 in','61.083 in'],['Primary steel + 10% connection allowance',f"{single['steel_with_connections_lb']:,.0f} lb",f"{two['steel_with_connections_lb']:,.0f} lb"],['Maximum gravity screen ratio',f"{single['max_ratio']:.3f}",f"{two['max_ratio']:.3f}"],['Maximum global service movement',f"{single['max_vertical_in']:.3f} in",f"{two['max_vertical_in']:.3f} in"]],[232,150,150])
p('The single-beam option is about 355 lb lighter in primary steel. The two-beam option shortens the longest joist span by one third, which may allow shallower or lighter secondary floor framing. The 9 psf floor dead-load allowance is held constant in this study; secondary joist sizing/cost has not been optimized, so the whole-floor weight advantage is not settled.')
p('Several single-beam positions have the same minimum tested primary weight. The midpoint is preferred because it minimizes the longest joist span between fixed T1 and T-N supports, not because the steel search found a unique mathematical optimum. This is a finite position/section comparison with selected companion-member upsizing.')
p('Both arrangements retain the preceding T1 option: W6×16 lower chord, W6×20 upper chord, HSS 2×2×1/8 verticals and HSS 2½×2½×1/8 end diagonals. The 1,000 lb lifted trolley load and provisional dynamic/equipment allowances are retained. All columns and the west O3 transfer beam remain at their existing coordinates.')
story.append(PageBreak());h('Floor framing comparison');story.append(Image(str(P/'beam-position-comparison.png'),width=532,height=532*10/15));p('Arrows inside the deck indicate north-south floor-joist spanning direction. Dimension chains show support spans; they are not W-beam spans. Both W beams still span 224.25 inches east-west between T-W and T-E. The floor remains open south of y = 72 inches. The deck extends to y = 255 inches, giving a 2-inch north overhang past T-N at y = 253 inches.')
p('B2 no longer needs to line up with W3: it transfers through T-W, which connects to the unchanged O3/W3 support line at y = 185 inches. That indirect load path is included in the connected model; its joints and restraint must be designed. No extra columns or garage-floor footings have been added by this comparison.')
p('The drawing shows a possible floor-support arrangement, not approved connection or fabrication details. The assumed T-N bearing detail must clear the north door, and any rail/seat connections must preserve trolley passage.')
story.append(PageBreak());h('Position and section sweep')
rows=[['B2 position(s), in','Rail section(s)','Steel lb','Ratio','Movement in','Screen']]
for x in sorted(rr,key=lambda x:(len(x['beam_y']),x['beam_y'])):
 rows.append([', '.join(f'{v:.2f}' for v in x['beam_y']),'/'.join(x['selection'][n+':beam'] for n in x['beam_names']),f"{x['steel_with_connections_lb']:,.0f}",f"{x['max_ratio']:.3f}",f"{x['max_vertical_in']:.3f}",'Meets' if x['feasible'] else 'Exceeds'])
table(rows,[102,116,70,65,89,90])
p('The limits are the inherited 0.90 combined-force screening metric and 0.75-inch maximum absolute global service movement. “Meets” means only those conditional gravity screens. The 130-inch trial exceeds the arbitrary movement threshold by about 0.003 inch; this does not demonstrate that such a layout is physically impossible. Candidate families and connection assumptions materially affect the result.')
p('For each layout, the Python model regenerates member intersections and the floor tributary-load distribution. It removes B3 and places the north floor reactions on T-N, checks the selected frame, upsizes failing companion families where possible, and tests W-rail section combinations. Other truss members are held fixed except required upsizing; a simultaneous global reoptimization could change the ranking.')
p('There are six one-beam positions and three two-beam layouts. Rail candidates are actual catalogue W sections at or below 8 inches actual depth. Trolley loads are sampled at nine locations on each rail and on T1, one operating trolley at a time. The whole connected frame is solved for each option; no truss is assigned the entire building load independently.')
story.append(PageBreak());h('What happens to T-N?')
table([['Case','T-N lower chord','Its controlling gravity ratio'],['One centered B2',single['selection']['T-N:lower'],f"{single['families']['T-N:lower']['ratio']:.3f}"],['Two equal-spaced beams',two['selection']['T-N:lower'],f"{two['families']['T-N:lower']['ratio']:.3f}"]],[200,190,142])
p('The T-N lower chord can serve as the north floor collector in this conditional model. Its own bending, axial force and connection behavior still matter: being part of a truss does not make local floor-bearing effects disappear. The truss shares load through its upper chord, web system and supporting columns.')
p('The one-beam option has little room below the chosen 0.75-inch global movement target. That target is not a code-specific relative beam deflection or trolley alignment check. This result should guide layout selection, not final member purchase. Joist deflection, the separately discussed 1,000 lb concentrated floor item, trolley flange-local checks and floor vibration still need member-level design.')
p('Unchanged limitations: first-order analysis; assumed rigid joints and fixed bases; assumed chord brace spacing; simplified W torsion without restrained warping; unverified roof collectors and diaphragm action; no completed site wind/seismic, connection, anchor or footing design. North floor seating into T-N and T-W/O3 transfer details are especially important for this revision.')
p('Reproduction: run run_sweep.py with the FreeCAD Python environment or equivalent NumPy/SciPy runtime; the balanced single-beam case is generated with BEAM_YS=[161.375] and LAYOUT=single-161 via test_layout.py. The scripts depend on the preceding revision-4 selected-options.json. Full per-layout selections, member demands and column reactions are in results/. make_plans.py and report.py generate this comparison. The AISC/Atlas section data and load references are those documented in revision 3.')
SimpleDocTemplate(str(P/'beam-position-comparison.pdf'),pagesize=(612,792),leftMargin=40,rightMargin=40,topMargin=35,bottomMargin=35).build(story);print('PDF created')
