import json,zipfile,xml.etree.ElementTree as E,hashlib
from pathlib import Path
P=Path(__file__).resolve().parent;ROOT=P.parents[1];book=ROOT.parent/'structural-analysis-v3/sources/aisc-v16.xlsx';z=zipfile.ZipFile(book);ns={'s':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'};ss=[''.join(x.itertext()) for x in E.fromstring(z.read('xl/sharedStrings.xml'))];rows=E.fromstring(z.read('xl/worksheets/sheet2.xml')).findall('s:sheetData/s:row',ns);catalog={}
for r in rows[1:]:
 d={''.join(x for x in c.attrib['r'] if x.isalpha()):ss[int(c.find('s:v',ns).text)] if c.attrib.get('t')=='s' else c.find('s:v',ns).text for c in r if c.find('s:v',ns) is not None}
 def f(k):
  try:return float(d.get(k,'nan'))
  except ValueError:return float('nan')
 if d.get('A')=='HSS' and f('I')==f('N') and 1.5<=f('I')<=6 and f('W')>=.125:
  name=f"HSS{f('I'):g}x{f('N'):g}x{f('W'):g}";catalog[name]=dict(name=name,type='HSS',d=f('I'),t=f('W'),tdes=f('X'),w=f('E'),A=f('F'),I=f('AM'),Iy=f('AQ'),Iz=f('AM'),S=f('AO'),Smajor=f('AO'),Sminor=f('AS'),J=f('AX'),C=f('AZ'),bt=f('AI'),Fy=50000.,aisc_label=d['C'])
 if d.get('A')=='W' and 5<=f('G')<=8.001:
  name=d['B'];catalog[name]=dict(name=name,type='W',d=f('G'),t=f('Q'),w=f('E'),A=f('F'),I=f('AM'),Iy=f('AQ'),Iz=f('AM'),S=f('AO'),Smajor=f('AO'),Sminor=f('AS'),J=f('AX'),Fy=50000.,bf=f('L'),tf=f('T'),tw=f('Q'),Zx=f('AN'),Cw=f('AY'),rts=f('BW'),ho=f('BX'),flange_ratio=f('AG'),aisc_label=d['C'])
(P/'catalog.json').write_text(json.dumps(catalog,indent=2));print('Catalog:',len(catalog),'stock sections')
b=json.loads((ROOT/'design-basis.json').read_text());b['roof'].update(main_dead_psf_surface=10.,cap_dead_psf_surface=7.);b['load_audit']={'main_roof_psf_surface':{'PV_or_glass_allowance':3.,'insulated_waterproof_metal_skin':3.,'secondary_purlins_and_supports':3.,'flashings_wiring_fasteners_margin':1.},'cap_roof_psf_surface':{'insulated_metal_skin':3.,'secondary_hip_frame':3.,'trim_margin':1.},'wall_psf':{'insulated_metal_panel':3.,'girts_trim_allowance':1.},'floor_dead_psf':{'plywood':2.5,'wood_joists_and_blocking':3.5,'hardware_minor_services_and_reserve':6.},'balcony':{'area_ft2':32*60/144,'dead_psf':12,'live_psf':100,'load_path':'Full gravity and16in eccentric moment assigned to TW lower chord; provisional conservative loading of west balcony y186..246.'},'primary_steel':'Catalog weight recalculated each solve plus10percent connection allowance; not in roof/floor psf.'};b['sources']={'PV':'https://www.canadiansolar.com/wp-content/uploads/sites/3/2026/01/CS-Datasheet-TOPHiKu6_All-Black_CS6.1-54TM-H_v1.4C25_F23_D2_TX.pdf','panel':'https://www.metlspan.com/wp-content/uploads/2024/11/MetlSpan-CF-PIR-Panel-Weights-1-1-1-002.pdf','roof_panel':'https://metlspan.com/wp-content/uploads/2022/11/PSF-Panel-Weights_2019.pdf','code':'https://www.sandiego.gov/development-services/codes-regulations','sections':'https://www.aisc.org/aisc/publications/steel-construction-manual/aisc-shapes-database-v160/'};b['section_database_sha256']=hashlib.sha256(book.read_bytes()).hexdigest();(P/'load-basis.json').write_text(json.dumps(b,indent=2))
# study_solver.py is the versioned load-path implementation; do not overwrite it here.
