from pathlib import Path
import json
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,Image,PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
P=Path(__file__).resolve().parent;r=json.loads((P/'selected-options.json').read_text());b=json.loads((P.parent/'structural-analysis-v3/results.json').read_text());s=getSampleStyleSheet();s['BodyText'].fontSize=10;s['BodyText'].leading=14;story=[]
def p(x):story.extend([Paragraph(x,s['BodyText']),Spacer(1,9)])
def h(x):story.append(Paragraph(x,s['Heading1']))
def table(rows):
 t=Table([[Paragraph(str(c),s['BodyText']) for c in row] for row in rows],colWidths=[172,120,120,120]);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e5edf1')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]));story.append(t)
h('T1: revisiting the upper/lower chord tradeoff')
p('Your proposed tradeoff works within the preliminary gravity model. The earlier one-family-at-a-time section search missed a better combination: a stronger upper chord allows a W6 lower chord. It also unnecessarily grouped all T1 web members together. The middle verticals can be lighter while the two compression diagonals remain larger.')
Bweight=sum(v for k,v in b['weights'].items() if k.startswith('T1:'))
table([['','Previous study','A: lighter option','B: W/W option'],['Lower chord','W8×24','W6×16','W6×16'],['Upper chord','HSS 2×2×1/8','HSS 4×4×3/16','W6×20'],['Vertical web members','HSS 2½×2½×1/8','HSS 2×2×1/8','HSS 2×2×1/8'],['Two end diagonals','HSS 2½×2½×1/8','unchanged','unchanged'],['Lower actual depth','7.93 in','6.28 in','6.28 in'],['T1 steel + allowance',f'{Bweight:.0f} lb',f"{r['A']['T1_weight']:.0f} lb",f"{r['B']['T1_weight']:.0f} lb"],['Whole primary frame + allowance',f"{b['steel_with_connections_lb']:.0f} lb",f"{r['A']['weight']:.0f} lb",f"{r['B']['weight']:.0f} lb"],['Max gravity screen ratio',f"{b['max_ratio']:.3f}",f"{r['A']['ratio']:.3f}",f"{r['B']['ratio']:.3f}"],['Max service movement',f"{b['max_vertical_in']:.3f} in",f"{r['A']['movement']:.3f} in",f"{r['B']['movement']:.3f} in"]])
p('All weights include the inherited 10% connection allowance. Both revised options also increase O3 from HSS 3×3×1/8 to HSS 3×3×3/16 because the stiffer T1 changes load sharing. B2 remains W8×31. The rest of the revision-3 section schedule remains fixed. The trolley load remains 1,000 lb lifted, plus provisional 100 lb equipment and 25% lifted-load dynamic allowance, one operating trolley at a time.')
p('Option B most closely matches your request for W sections on both chords; option A saves more steel. Both reduce the nominal floor-level rail depth by 1.65 inches. The top chord and its connections still need a physical placement/detailing decision: the model preserves architectural centerlines, so it does not yet prove final headroom, roof height or flange clearances.')
story.append(PageBreak());h('Two candidate T1 layouts');story.append(Image(str(P/'T1-comparison.png'),width=532,height=532*9/13));p('These layouts preserve the open middle bays. They are connected rigid-frame/truss idealizations, not pin-jointed open-web joists. A stronger top chord does not eliminate the need for the web members and joints to transfer shear, bending and compression.')
p('The 2½-inch web designation looks larger than the old 2-inch upper chord, but the relevant comparisons are area, bending stiffness, unsupported length and connection demands. Size ordering alone cannot determine whether a truss is sensible. The previous result was especially incomplete because it did not verify that the small top chord could provide the assumed rigid joints.')
story.append(PageBreak());h('Why the end diagonals stay larger')
p('For the usual simply supported truss under downward loading, your intuition is correct: the top chord is generally in compression and the bottom chord in tension. Their axial forces are approximately equal and opposite in the simple truss bending model; compression buckling often makes the top chord more demanding. Here, floor loads and the moving trolley also bend the bottom chord locally, and the open bays require joint/frame bending action. The bottom chord cannot be designed as a tension tie alone.')
p('The controlling web member in the previous T1 calculation was diagonal M021: approximately 12.1 kip compression (12,100 lb) in its governing factored case. These end diagonals are about 92.6 inches long. A light compression member can buckle before reaching its steel yield strength. Making the upper chord heavier does not by itself solve that diagonal buckling problem.')
p('The revised search evaluated 75 joint chord/web combinations with the rest of the frame fixed, repeated them with companion-member upsizing, then tested 12 combinations with verticals and diagonals sized separately. These are bounded comparisons, not a global optimum. All 12 split-web combinations met the inherited 0.90 strength-screen and 0.75-inch global movement limits.')
p('Angle webs are a reasonable option to investigate for an efficiently triangulated joist, but they are not a drop-in substitute for the rigid HSS members in these open bays. Their weak-axis and flexural-torsional buckling, eccentric gusset connections and actual end restraint need analysis. No angle-web capacity is claimed in this comparison. Splitting the member roles was the immediate improvement supported by the current model.')
p('<b>Status:</b> These are conditional gravity candidates. The unchanged limitations of revision 3 still apply: assumed 72-inch chord restraint, unverified rigid connections, first-order analysis, simplified W torsion, no completed lateral system, and no local trolley-wheel/flange or foundation design. Do not use the comparison as a lifting rating or construction schedule.')
p('Sources: <link href="https://steeltubeinstitute.org/resources/square-rectangular-hss-hss-moment-connections/" color="blue">Steel Tube Institute: Vierendeel moment connections</link>; <link href="https://steeljoist.org/wp-content/uploads/2021/09/SJI_Part-1-Evaluation-and-Modification-of-Open-Web-Steel-Joists-and-Joist-Girders_091021-1Slide.pdf" color="blue">Steel Joist Institute: open-web joist components</link>. Section properties and load basis are retained from the AISC/Atlas source files in revision 3.')
SimpleDocTemplate(str(P/'T1-chord-web-comparison.pdf'),pagesize=(612,792),leftMargin=40,rightMargin=40,topMargin=35,bottomMargin=35).build(story)
print('PDF created')
