from pathlib import Path
import json
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,Image,PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
P=Path(__file__).resolve().parent;c=json.loads((P/'checks.json').read_text());s=getSampleStyleSheet();s['BodyText'].fontSize=10;s['BodyText'].leading=14;story=[]
def p(x):story.extend([Paragraph(x,s['BodyText']),Spacer(1,9)])
def h(x):story.append(Paragraph(x,s['Heading1']))
def table(rows,widths):
 t=Table([[Paragraph(str(v),s['BodyText']) for v in row] for row in rows],colWidths=widths,repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e5eeee')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]));story.append(t)
h('Roof first, old roof removed later')
p('<b>Conditional geometric finding: a complete raised roof-support truss can fit above the modeled old roof at T1.</b> A roof-only truss with an overall 36-inch envelope leaves approximately 12–14 inches of nominal clearance using the earlier wall footprint and the two roof-rise descriptions. That is enough to justify developing this alternative, but it is not a structural capacity or erection-clearance approval.')
p('The existing floor-height T1 cannot simply be installed intact around the old roof. Its lower chord and webs cross that roof. An interior post creates a possible support point; it does not eliminate this geometric conflict. The proposed solution is a new, complete, shallower T1-R at roof level, followed by separate or deliberately staged floor/trolley framing later.')
p('I reviewed the linked task, “Plan phased garage roof construction.” Its latest redraw uses a provisional 286.25-inch north–south wall, whereas this project previously used your correction of 249 inches. It also replaces the short ridge with a single peak. Both roof envelopes have been checked here. No source geometry has been silently overwritten.')
table([['Roof basis','Old roof at T1','Space to new roof underside','Gap below 36-in truss']]+[[x['name'],f"{x['T1_old_roof_max']:.2f} in",f"{x['total_gap']:.2f} in",f"{x['remaining_vertical_gap']:.2f} in"] for x in c['cases']],[205,100,117,110])
p('All elevations are above nominal slab/ground datum. T1 is at y = 69.75 inches north of the south wall. New roof underside at that station is 183.14 inches. The trial truss occupies z = 147.14 to 183.14 inches. Clearance excludes actual eaves, roof thickness, member/connection projections, deflection, tolerances and working space. The trial depth is a geometric envelope, not a selected steel design.')
p('<b>North-row conflict:</b> T-N at y = 253 is four inches outside a 249-inch wall, but 33.25 inches inside a 286.25-inch wall. With the longer model, the present north frame cannot be called exterior and the existing proposed roof footprint also needs reconciliation. Even four inches may be insufficient to clear actual eaves, column widths, base plates and excavation.')
story.append(PageBreak());h('A roof-first T1 with an interior bearing');story.append(Image(str(P/'roof-first-concept.png'),width=532,height=532*10/13))
p('The illustration places the west bearing on the exterior W2 line at x = -32 inches and a provisional interior post at x = 224.25 inches, 25.25 inches inside the east wall. This makes a 256.25-inch bearing span, longer than the earlier 224.25-inch T1. The refrigerator/cabinet location has not been established; this interior coordinate is an example, not a selected post position.')
p('The gray area is the retained building/roof envelope, not a surveyed model of individual rafters and ties. A post can pass through a locally opened and weather-sealed roof area, but its location must be coordinated with actual roof framing. Moving a refrigerator or cabinet alone does not create a foundation or establish a clear path through rafters.')
story.append(PageBreak());h('How the supports and trusses change')
table([['Location','Roof-first implication'],['T-N','Potential exterior full-height frame, once the wall length and eave clearance are settled. It must be connected to a braced return; a single standing truss is not a stable three-dimensional structure.'],['T-S','May move outside the south eave, on its own designed supports. Moving it changes its height under the 30-degree roof and the south roof span; the drawing uses an illustrative location only.'],['West side','The exterior column line at x = -32 is promising. The current T-W line at x = 0 is above the wall/eave, so using exterior full-height posts directly changes its transfer arrangement. Check shelter and access conflicts.'],['T1-R','A complete raised roof truss, with all chords and diagonals present before it carries the new roof. Interior post requires an independent footing and lateral restraint.'],['T-E','Still lies 25.25 inches inside the east wall. Its existing low chord/web system intersects the old roof. It must also be redesigned as a roof-level member or otherwise relocated; solving T1 alone is insufficient.'],['Future floor and trolley rails','Install after old roof removal. The prior W6 lower chord worked as part of a deep truss and is not automatically adequate as a separate floor beam. Either design independent floor framing or engineer the eventual connection to the roof truss, including staged loads.']],[100,432])
p('The interior footing would normally require a localized slab opening and excavation to a designed bearing system. Do not put the post on the weak slab or rely on a larger steel base plate to make the slab adequate. The post in this sketch is roughly 12 ft 3 in to its bearing, taller than the earlier 98.5-inch columns, so earlier post capacity estimates do not apply unchanged.')
p('The original roof analysis routed purlins east-west onto T-E and T-W. A roof-first system using T1-R as a primary transverse support may change that direction or add roof-level collectors. The next model must explicitly resolve that routing; a clearance drawing is not evidence that every new roof load has a path to the foundations.')
story.append(PageBreak());h('Construction states to design')
for title,text in [
('1. Survey and foundations','Confirm the wall footprint, old ridge/eaves, interior post location, roof framing, utilities, overhead power lines and access for steel placement and old-roof removal. Install independently designed foundations and anchor points without undermining existing foundations.'),
('2. First stable exterior bay','Erect a connected north/west or south/west assembly with the necessary return framing and bracing. The structural engineer/erector determines the actual sequence, temporary guys, anchors and lifting arrangements; this document does not prescribe a crane or rigging plan.'),
('3. Interior post and complete roof-only frame','Make the planned local roof opening, weather-seal the post penetration, and complete T1-R and the redesigned east/west roof supports. Provide stability in both directions without relying on the old roof or a future floor diaphragm.'),
('4. New roof complete; old roof still present','Install roof secondary framing, bracing, weatherproofing/solar assembly and drainage. This must be a stable, durable building state if it will remain for months or years. Check open-sided wind/uplift and construction loads, not only the eventual enclosed building.'),
('5. Old roof removal under the new roof','Provide a removal route and establish how the old walls stay restrained as rafters, ties and roof diaphragm are taken away. Do not presume the old roof is redundant merely because a new roof is overhead.'),
('6. Loft and final enclosure','Install floor beams/joists and the trolley system, then complete enclosure and final bracing. Design any transfer of load or staged connections explicitly. Roof dead load applied before later framing is connected does not automatically redistribute as if the whole structure were erected simultaneously.')]:
 p('<b>'+title+'</b><br/>'+text)
p('Keeping the garage usable between operations is plausible. Overhead erection and demolition require controlled work zones; ongoing occupancy beneath those operations is not assumed.')
p('Structural stability throughout erection is addressed in <link href="https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.754" color="blue">OSHA 1926.754</link>. Assessment of the existing structure before demolition is addressed in <link href="https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.850" color="blue">OSHA 1926.850</link>. These references identify planning requirements, not an engineered or locally approved erection plan.')
p('<b>Next design step:</b> after the footprint and interior post location are confirmed, build a separate roof-first structural model, then check each construction state and the final floor-bearing arrangement. Do not reuse the prior truss sizes or merely omit conflicting members from that model. No member size, footing size, lifting capacity or temporary-bracing capacity is assigned in this geometric study.')
SimpleDocTemplate(str(P/'roof-first-feasibility.pdf'),pagesize=(612,792),leftMargin=40,rightMargin=40,topMargin=35,bottomMargin=35).build(story)
print('Created roof-first feasibility PDF')
