from pathlib import Path
import json,html
from fractions import Fraction
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak,Image,KeepTogether
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
P=Path(__file__).resolve().parent;r=json.loads((P/'results.json').read_text());l=json.loads((P/'load-path.json').read_text());mem=json.loads((P/'physical-members.json').read_text());secs=json.loads((P/'sections.json').read_text());styles=getSampleStyleSheet();styles['BodyText'].fontSize=8.5;styles['BodyText'].leading=11.5
styles['Heading1'].fontSize=18;styles['Heading2'].fontSize=12
story=[];md=[]
def para(s):story.append(Paragraph(s,styles['BodyText']));story.append(Spacer(1,6));md.append(s+'\n')
def head(s):story.append(Paragraph(s,styles['Heading1']));md.append('\n## '+s+'\n')
def sub(s):story.append(Paragraph(s,styles['Heading2']));md.append('\n### '+s+'\n')
def table(rows,widths=None):
 t=Table([[Paragraph(html.escape(str(x)),styles['BodyText']) for x in row] for row in rows],colWidths=widths,repeatRows=1,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e4eef0')),('VALIGN',(0,0),(-1,-1),'TOP'),('LINEBELOW',(0,0),(-1,0),.5,colors.grey),('TOPPADDING',(0,0),(-1,-1),3),('BOTTOMPADDING',(0,0),(-1,-1),3)]));story.append(t);story.append(Spacer(1,8));md.extend([' | '.join(map(str,row)) for row in rows])
def page():story.append(PageBreak())
def fmt(name):
 s=secs[name]
 return name if s['type']=='W' else f"HSS {s['d']:g} x {s['d']:g} x "+{.125:'1/8',.188:'3/16',.25:'1/4',.313:'5/16',.375:'3/8',.5:'1/2',.625:'5/8'}[s['t']]
def image(name,w=532):
 from reportlab.lib.utils import ImageReader
 a,b=ImageReader(str(P/name)).getSize();story.append(Image(str(P/name),width=w,height=w*b/a))
def foot(c,d):c.setFont('Helvetica',8);c.drawString(40,23,'Garage | Conditional gravity member design | 8 September 2026');c.drawRightString(572,23,str(d.page))
head('Truss-by-truss design and calculation review')
para('<b>Revision 3: connected model with W-section trolley rails.</b> This package gives an explicit candidate geometry and member schedule for T-S, T1, T-E, T-W and T-N. It traces loads from the framing plan into each truss, records the controlling member checks, and tests lighter alternatives. It remains a preliminary first-order gravity design study, not a fabrication or construction design.')
para('The model has a feasible local result under its selected screens: <b>7,495 lb</b> of primary steel plus a 10% connection-weight allowance, a highest strength screening ratio of <b>0.899</b>, and a largest service vertical movement of <b>0.730 inch</b>. This is approximately 1,738 lb (19%) below the prior 9,233 lb HSS study. Separating upper and lower chords, changing B2 end behavior and using W rails all changed this comparison; the savings cannot be attributed to one change alone.')
table([['Truss','Lower chord','Upper chord(s)','Webs / posts']]+[[g]+[fmt(r['selection'][g+':'+role]) for role in ['lower','upper','web']] for g in ['T-S','T1','T-E','T-W','T-N']],[55,159,159,159])
para('<b>B2 is W8X31, 8.00 inches actual depth. T1 remains a full truss with a W8X24 bottom chord, 7.93 inches deep.</b> W8X24 means nominal 8-inch depth and 24 lb/ft; the 24 is not a wall thickness. Both rails need actual trolley flange compatibility and local wheel-load checks before any lifting rating can be assigned.')
para('The small T-S members are at the bottom of the tested catalogue, not proven absolute minima. Their low demand depends on roof purlins spanning east-west to T-W/T-E. Wind, facade detailing and connection fabrication can set substantially larger minimum sizes. All schedules in this report are conditional candidates.')
sub('What this delivers, and what remains')
para('Delivered: truss geometry with member IDs, load-path actions, trial sizes, compression/bending screens, moving-hoist gravity cases and a recorded lighter-section search. Remaining: site lateral loads and stability, bracing design, joint design, trolley local flange effects, cap collectors, column bases and foundations. These unresolved checks can invalidate the light sections shown here.')
page();head('1. Top-down load path');image('load-plan.png',475)
para('Blue horizontal members are beams. Each colored perimeter line represents the full-height truss on its individual elevation sheet. No added gravity bearing is assigned to the existing walls, slab or cabinets. S1 is modeled but still has no upper-frame connection. S3 is assumed present.')
page();head('2. Loads enter once, then transfer between members')
para('Roof purlins are assumed to span east-west onto T-W and T-E. Floor joists span north-south onto T1, B2 and B3. The connected stiffness model then redistributes the reactions through the trusses, transfer beams and columns. A load transferred from B2 into T-E is not added again as building weight.')
table([['Group','Direct service load, lb','Sum of vertical actions from connected frame, lb']]+[[g,f"{l['direct_service_load_lb'][g]:,.0f}",f"{sum(x['Fz'] for x in l['interfaces'][g]):,.0f}"] for g in ['T-S','T1','B2','B3','T-E','T-W','T-N']],[85,165,282])
para('Direct load includes the assigned roof/floor/wall load and the member group self-weight, for D + perimeter-storage live load + roof live load. Positive connection action is upward on the named group. Connection actions can include both upward and downward forces at different joints. The equality above is a group equilibrium check, not a statement that each truss carries the entire building.')
sub('Load cases and trolley assumptions')
para('The inherited floor is 284.98 sq ft, with 125 psf live load in 36-inch north/east/west storage bands and 40 psf elsewhere. Roof live load is 20 psf on horizontal projection. Dead allowances are 9 psf floor, 9.5 psf actual solar roof surface, 6.6 psf cap surface, 4 psf gross upper walls, and the balcony/guard allowances from revision 2. The new frame self-weight is recalculated for every trial.')
para('A single operating trolley is tested on either B2 or T1 at nine positions, from x = 0 to 224.25 inches. Each position adds 1,350 lb downward: the confirmed 1,000 lb lifted load, a provisional 25% dynamic increment, and an assumed 100 lb trolley/hoist. This is a sampled position envelope, not a continuous moving-load proof. The actual equipment weight, wheel spacing, flange contact and dynamic requirements must replace these assumptions. Simultaneous use of two hoists is not included.')
para('Service = D + storage + roof live, with and without each trolley position. Strength = 1.2D + 1.6 storage + 0.5 roof live, with trolley gravity factored 1.6; also 1.2D + storage + 1.6 roof live without trolley. These are selected study combinations, not the full legal design envelope. Full-area 125 psf and lateral cases from revision 2 are not requalified by this revision.')
sub('Movement criterion')
para('The search holds maximum absolute vertical movement at any model node to 0.75 inch. This is a study-wide tolerance, not an L/360 certification for every beam or a hoist manufacturer alignment limit. Maximum movement with the trolley is 0.730 inch; the no-trolley storage case is 0.726 inch. Member-relative deflection, floor vibration and machinery tolerances still need review.')
page();head('3. How the member sizes are found')
para('Each truss is kept as a complete connected assembly. Upper chords, lower chords and webs are sized as separate families, while the global model retains their common nodes. Changing a family changes both stiffness and self-weight, so the entire frame is solved again after every trial. The geometry itself is held fixed; this run is a section search, not a truss-topology optimization.')
for s in ['Start with the earlier feasible HSS study, replace B2 and the T1 lower chord with real W-section candidates, and release B2 end bending rotations to represent shear seats. B2 end torsion remains restrained and needs a real detail.', 'Increase families that fail the selected combined-force screen. Then test every lighter catalogue section in each family and accept the first one that keeps the whole frame within the strength and movement screens.', 'Repeat complete sweeps until no family can be reduced. Three sweeps were run; the final sweep accepted zero reductions. This is a coordinate-wise local stopping point. Simultaneous section swaps, different bracing or different panel geometry can produce a different result.']:
 para(s)
sub('Strength calculations used')
para('Steel E = 29,000 ksi and specified Fy = 50 ksi. Compression uses r = sqrt(Imin/A), Fe = pi²E/(KL/r)², and Fcr = Fy(0.658)^(Fy/Fe) when Fy/Fe ≤ 2.25, otherwise 0.877Fe. Available compression Pc = 0.9 Fcr A; gross-section tensile yield Pt = 0.9 Fy A. Net-section fracture and connection rupture are not checked.')
para('HSS elastic bending screens use 0.9 Fy S about each axis. W major-axis bending additionally uses AISC F2 lateral-torsional buckling with Cb = 1.0, capped at elastic yield. Slightly noncompact W flanges are conservatively capped at 0.9 × 0.7 Fy S rather than credited with plastic capacity. This is deliberately a screening implementation, not every AISC limit state.')
para('Combined metric = max(Ncompression/Pc, Ntension/Pt) + |Mmajor|/Mc-major + |Mminor|/Mc-minor. A separate approximate shear-plus-torsion ratio is checked, and the larger value controls. The search limit is 0.90. This conservative linear metric is not a full AISC H1/H3 code check. All force values are first-order; no second-order stability reduction has been included.')
para('<b>Required restraint assumptions:</b> K = 1; chords and W members have effective lateral/torsional brace spacing at most 72 inches, limited by their original member length; web members use their original full length; columns use 98.5 inches. Numerical subdivisions never shorten the assumed buckling length. Those brace points and their force/stiffness requirements have not been designed. W torsion uses Saint-Venant stiffness only; restrained warping and flange distortion remain unresolved.')
para('Closed-form solver tests cover cantilever bending, axial extension, torsion, simple-span point loading, end releases, and distinct strong/weak W-section axes. Load-path recovery checks each member group equilibrium. These verify the calculation implementation at this level, not the physical assumptions.')
# Five trusses, each drawing + member calculations + lighter alternatives.
for g in ['T-S','T1','T-E','T-W','T-N']:
 page();head(g+' — geometry and load transfer');image(g+'-design.png')
 dims=[d for d in mem.values() if d['group']==g];allpts=[pt for d in dims for pt in d['ends']];dim=1 if g in ['T-E','T-W'] else 0
 span=max(p[dim] for p in allpts)-min(p[dim] for p in allpts);height=max(p[2] for p in allpts)-98.5
 para(f'Overall analytical span {span:.2f} in; maximum depth above wall-top line {height:.2f} in. Physical member IDs match the force table. Member lengths are analytical centerline lengths, not cut lengths. Joints, offsets and weld gaps remain to be detailed.')
 table([['Role','Candidate','Governing screen','Case']]+[[role,fmt(r['selection'][g+':'+role]),f"{r['families'][g+':'+role]['ratio']:.3f}",r['families'][g+':'+role]['case']] for role in ['lower','upper','web']],[65,200,75,192])
 para('The bottom arrows show only vertical interaction with adjacent framing in the no-trolley service case. Distributed direct loads are summarized in the title. Horizontal actions and joint moments also exist; connection-actions.csv contains all six components. A connection cannot be designed from the vertical arrows alone.')
 if g=='T1':para('T1 retains its full 84.64-inch truss depth. The W8X24 is only the lower chord/trolley rail. Open middle bays require moment-resisting joints; their lower chord is not assumed to act alone as a full-span simply supported beam.')
 if g=='T-W':para('The rear opening is deliberately untriangulated. Its frame action helps explain why T-W retains a much larger upper chord than T-E. Do not add diagonals through the balcony/door opening without an architectural revision.')
 if g=='T-N':para('The door interrupts triangulation below the upper band. The middle horizontal line and upper band are both in the upper-chord family. Portal-frame joint action around the opening has not been fabricated or verified.')
 page();head(g+' — member force and capacity checks')
 rows=[['ID / role','Length in','Comp. / tens. kip','Major / minor M kip-ft','Ratio']]
 members=sorted([(k,d) for k,d in r['physical_members'].items() if d['group']==g])
 for k,d in members:rows.append([k+' / '+d['family'].split(':')[1],f"{mem[k]['length_in']:.1f}",f"{d['Nc']/1000:.2f} / {d['Nt']/1000:.2f}",f"{d['My']/12000:.2f} / {d['Mz']/12000:.2f}",f"{d['ratio']:.3f}"])
 table(rows,[105,70,120,155,82])
 para('Each row reports the controlling sampled load case and finite-element segment within that physical member. Axial and moment components conservatively take the larger end value within that segment; they are not a single connection force vector. The CSV records the governing case, effective buckling length, capacities, shear and torsion for every row.')
 sub('Worked check: governing member in this truss')
 k,d=max(members,key=lambda kv:kv[1]['ratio']);s=secs[d['section']]
 para(f"{k}: {fmt(d['section'])}; governing case {d['case']}. Assumed effective buckling length {d['Lb']:.1f} in. Available compression {d['Pc']/1000:.2f} kip, tensile yield {d['Pt']/1000:.2f} kip, major bending {d['Mmajor']/12000:.2f} kip-ft, minor bending {d['Mminor']/12000:.2f} kip-ft.")
 ax=max(d['Nc']/d['Pc'],d['Nt']/d['Pt']);ma=d['My']/d['Mmajor'];mi=d['Mz']/d['Mminor'];shear=d['V']/d['Vc']+d['T']/d['Tc']
 para(f"Axial term = {ax:.3f}; major-bending term = {ma:.3f}; minor-bending term = {mi:.3f}. Sum = {ax+ma+mi:.3f}. Separate shear/torsion screen = {shear:.3f}. Governing metric = {d['ratio']:.3f}, against the study target 0.900. This conditional screen does not include joint capacity or second-order effects.")
 page();head(g+' — why not make it lighter?')
 trials=[x for x in r['lower_trials'] if x['family'].startswith(g+':')]
 table([['Family','Lighter trial','Saved lb','Global ratio','Global movement in']]+[[x['family'].split(':')[1],fmt(x['trial']),f"{x['weight_saving_lb']:.1f}",f"{x['max_ratio']:.3f}",f"{x['max_vertical_in']:.3f}"] for x in trials],[65,195,65,85,122])
 para('Each row changes only that family and then re-solves the entire connected building. The illustrated trial is the next lighter catalogue entry by weight; the full search also tested other lighter entries. A ratio above 0.900 or movement above 0.750 inch rejects the trial. A rejection can be caused by a different member because stiffness changes redistribute loads.')
 if len(trials)<3:para('A missing role is already at the lightest candidate in the tested catalogue. That is a catalogue floor, not proof of a physical minimum and not a fabrication recommendation.')
 para(f"Selected {g} weight including 10% connection allowance: {sum(v for k,v in r['weights'].items() if k.startswith(g+':')):,.0f} lb.")
 sub('Connection actions to carry forward')
 rr=l['interfaces'][g];table([['Node','Connected group(s)','Vertical lb','Moment magnitude kip-ft']]+[[x['node'],', '.join(x['other_groups']),f"{x['Fz']:+,.0f}",f"{(x['Mx']**2+x['My']**2+x['Mz']**2)**.5/12000:.2f}"] for x in rr],[50,240,100,142])
 para('These are service connection actions, included to expose the assumed transfer path. They are not a factored connection design schedule. The moment magnitude is for orientation only; connection design must use the signed component vectors and all governing combinations. Welds, gussets, bolts, HSS face yielding and local distortions remain unqualified.')
page();head('B2 and the trolley rails')
table([['Rail','Candidate','Actual depth','Screen ratio'],['B2',fmt(r['selection']['B2:beam']),f"{secs[r['selection']['B2:beam']]['d']:.2f} in",f"{r['families']['B2:beam']['ratio']:.3f}"],['T1 lower chord',fmt(r['selection']['T1:lower']),f"{secs[r['selection']['T1:lower']]['d']:.2f} in",f"{r['families']['T1:lower']['ratio']:.3f}"]],[115,185,115,117])
para('B2 is a beam and T1 is a truss. B2 uses end bending releases to model shear seats; torsional restraint remains assumed. T1 lower chord remains connected to its posts, diagonal end bays and upper chord. The rest of T1 participates in carrying the trolley and floor loads.')
para('Nine loaded positions were checked on each rail, one trolley at a time. The position label @3/8 means three-eighths of the way from the west end. Moving load is applied on the rail centerline for vertical global analysis. Wheel spacing, unequal wheel loads, longitudinal acceleration, lateral force, flange-local bending, web tension and restrained warping are not resolved by that idealization.')
para('<b>No 1,000 lb lifting rating is established by these results.</b> The actual trolley specification is needed to check flange fit, wheel contact and the relevant hoist standard/dynamic factors. Both the full building load and the moving load must be retained in the final checks. Bolted splices, end stops and stiffeners must preserve trolley travel.')
sub('Whole-frame reactions remain important')
table([['Column','Service storage reaction, lb']]+[[k,f'{v:,.0f}'] for k,v in r['cases']['service storage']['columns'].items()],[265,267])
para('These revised reactions supersede the earlier values only for this conditional configuration. Columns remain 4 x 4 x 3/16 HSS trial members. Axial capacity alone does not establish column or footing adequacy. The assumed rigid bases and bracing have not been verified.')
page();head('Remaining engineering and reproducibility')
para('The geometry still contains architectural-line approximations at joints, rather than fully detailed section-centroid offsets. Upper HSS chord sizes as small as 2 inches may be impractical when connected to the much larger lower chords. Cost, weld access, tube-face capacity and required bracing can make a heavier but simpler truss preferable.')
para('This revision does not optimize geometry, connection weight or purlin profiles. Roof purlin routing is assumed, and the hip-cap rafters and collectors are represented only by loads. The frame is not a complete lateral-force-resisting system. Wind, seismic, rain/ponding, second-order effects, diaphragm actions, uplift connections and foundation capacity must be checked before members are finalized.')
para('The recorded stopping point is local and conditional. It answers “what lighter members survive these explicit gravity screens in this connected model?” It does not answer “what is the lightest safe building?” That latter answer requires the unresolved physical details and site design loads.')
sub('Files and commands')
para('engineer.py builds the revised connected model, performs the grouped section search and writes results.json. geometry_builder.py preserves the prior geometry and load routing. frame_solver.py now distinguishes W-section strong and weak axes. Run verify.py for benchmarks; run engineer.py, then detail.py for member IDs, CSVs and figures; run report.py with ReportLab to produce this document. NumPy, SciPy and Matplotlib are needed for the calculation/figures.')
para('Inputs are frozen under inputs/. The prior HSS starting selection is stored as baseline-selection.json. Physical member lengths and coordinates are in physical-members.json; individual demand/capacity data are in member-checks.csv; signed service joint actions are in connection-actions.csv; the complete section-search history and lighter trials are in results.json. The source ZIP includes the AISC catalogue download used for the W data.')
sub('Primary references')
for title,url in [('AISC Shapes Database v16.0','https://www.aisc.org/aisc/publications/steel-construction-manual/aisc-shapes-database-v160/'),('Official AISC spreadsheet downloaded for this study','https://cloud.aisc.org/biggie_bin/aisc-shapes-database-v160-2.xlsx'),('Atlas square HSS properties','https://www.atlastube.com/wp-content/uploads/2018/04/A500-Square-Current.pdf'),('AISC specification formula reference, E3 and F2','https://www.aisc.org/globalassets/aisc/publications/standards/a360-16w-rev-june-2019.pdf'),('AISC discussion of bottom-flange loading and hoist impact','https://www.aisc.org/globalassets/modern-steel/steel-interchange/2005/2005v02_si_web.pdf'),('San Diego adopted codes','https://www.sandiego.gov/development-services/codes-regulations')]:para(f'<link href="{url}" color="#176986">{title}</link>')
para('The cited formula reference and diagnostic load assumptions do not establish compliance with the currently adopted California code. A licensed structural engineer must reconcile the final design basis, details and applicable standards before construction.')
SimpleDocTemplate(str(P/'truss-design-and-calculations.pdf'),pagesize=(612,792),leftMargin=40,rightMargin=40,topMargin=35,bottomMargin=42).build(story,onFirstPage=foot,onLaterPages=foot)
(P/'README.md').write_text('\n'.join(md));print('PDF created')
