"""Create the review PDF from saved analysis results; no analysis is rerun."""
from pathlib import Path
import json, html
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
P=Path(__file__).resolve().parent
r=json.loads((P/'results.json').read_text()); sec=json.loads((P/'secondary-checks.json').read_text())
styles=getSampleStyleSheet();styles['BodyText'].fontSize=9;styles['BodyText'].leading=13
story=[];md=[]
def p(t):
 story.append(Paragraph(t,styles['BodyText']));story.append(Spacer(1,7));md.append(t+'\n')
def h(t):
 story.append(Paragraph(t,styles['Heading1']));md.append('\n## '+t+'\n')
def table(rows,widths=None):
 data=[[Paragraph(html.escape(str(c)),styles['BodyText']) for c in row] for row in rows]
 t=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e4edf2')),('VALIGN',(0,0),(-1,-1),'TOP'),('LINEBELOW',(0,0),(-1,0),.8,colors.grey),('BOTTOMPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),5)]));story.append(t);story.append(Spacer(1,10));md.extend([' | '.join(map(str,row)) for row in rows])
def page():story.append(PageBreak())
def footer(c,d):
 c.setFont('Helvetica',8);c.setFillColor(colors.grey);c.drawString(40,25,'Garage | Preliminary first-order structural screen | 8 September 2026');c.drawRightString(572,25,str(d.page))
h('Garage: weight, load paths and steel framing')
p('<b>Review study, not construction sizing.</b> This calculation establishes a conditional gravity-load baseline and tests practical member families. It does not establish a final safe structure or a global minimum-weight design. Existing walls, cabinets and slab receive no added gravity credit.')
p('Your two-stage plan is useful with one correction: equilibrium alone cannot determine how redundant supports share load. Assuming all beams infinitely rigid does not resolve that sharing. This study first assigns tributary loads, then uses finite beam, truss and column stiffness to calculate reactions and member forces.')
dead=sum(r['dead_load_nonprimary_lb'].values())+sum(r['steel_weight_by_group_lb'].values())
table([['Finding','Result'],['Permanent construction weight',f'{dead:,.0f} lb, including 10% primary connection allowance'],['Primary steel plus connection allowance',f"{sum(r['steel_weight_by_group_lb'].values()):,.0f} lb"],['Occupied service case','44,734 lb total downward load'],['Heavy perimeter-storage service case','55,747 lb total; N2 about 14,999 lb'],['B2 depth target','An 8-inch HSS candidate survives the selected gravity screen; it is not a final member selection.'],['Main unresolved issue','Connections, lateral bracing and real load transfer govern whether these results are achievable.']], [185,347])
p('Stored contents remain live load even when left in place. The stated 2,000 lb of contents is not used as a substitute for floor design live load. A 1,000 lb concentrated item is a separate local floor problem.')
p('Simple changes did not deliver a lighter frame: the triangulated trial weighs 9,263 lb, and triangulation with B2/B3 shear seats weighs 9,955 lb, versus 9,233 lb baseline. These are bounded-search comparisons, not proof that triangulation cannot help.')
h('What I would resolve next')
p('Detail the south load path and connect S1 deliberately; choose a real lateral bracing system; locate the heavy storage bearing points; then redesign the truss panel layout and joints together. Repeat the section search after those decisions. Do not buy the candidate sections from this report.')
page();h('Geometry and load routing')
p('All architectural beam and truss bottom lines are at 98.5 inches above nominal ground. The analytical lines idealize those architectural lines as member centerlines; actual centroid offsets and connection eccentricities still need detailing. The main roof rises 30 degrees from T-SO; the rear cap has the restored low hip. The cap surface weight is included, but its rafters and collectors are not explicitly modeled.')
table([['Item','Analytical geometry / assumption'],['Main loft','18 ft 8-1/4 in east-west by 15 ft 3 in north-south; 284.98 sq ft. South edge 72 in north of south wall.'],['Floor joists','North-south, supported at T1 (69.75 in), B2 (185 in) and B3 (249 in). North deck edge 255 in.'],['Roof purlins','East-west onto T-W and T-E, with the east overhang carried by cantilever reaction factors. This choice strongly affects truss demand.'],['T-E / T-W','Longitudinal trusses. Roof loads enter their upper lines; floor loads enter through transverse framing.'],['T-S / T1','Open-bay baseline modeled with rigid frame joints, not pin-jointed rectangular trusses.'],['T-N','Full upper north wall truss with the door opening. B3 remains the floor-level north beam.'],['T-SO','A beam despite its historical name. Its south support transfer is not a construction detail.'],['Columns','All nine shown columns included, with S3 assumed active. S1 has no connection to upper framing and therefore carries only its own weight.'],['Foundations','Fixed bases initially assumed. Existing footing dimensions and soil capacity are not verified. No foundation sizing is claimed.']], [110,422])
p('Upper wall loads are placed on the perimeter framing. The east wall load includes its offset from T-E. Roof overhang effects are included through reaction factors and equivalent moments. The small balcony north overhang is clamped to the last support station; this and the roof-cap load smearing require refinement. Existing shelter capacity is excluded.')
page();h('Permanent weight budget')
table([['Component','Weight, lb']]+[[k,f'{v:,.0f}'] for k,v in r['dead_load_nonprimary_lb'].items()]+[['Primary steel + 10% connection allowance',f"{sum(r['steel_weight_by_group_lb'].values()):,.0f}"],['TOTAL',f'{dead:,.0f}']],[420,112])
p('The solar-slope budget is 9.5 psf of actual surface: approximately 2.4 PV, 2.6 metal/foam panel, 1.0 waterproofing/details and 3.5 secondary framing. Cap budget is 6.6 psf of actual surface. These are allowances, not a selected tested roof system. The manufacturer panel reference is steel-faced; the desired aluminum-faced assembly must be priced and weighed separately.')
p('Measured roof surfaces in the model total 418.43 sq ft of solar slope and 239.58 sq ft of hip cap. Their intersecting takeoff is retained conservatively. Wall weight uses gross area with no opening deductions. Primary connection weight is an allowance, with no connection stiffness or capacity established.')
h('Load cases')
table([['Service case','Total load, lb','Max vertical movement, in']]+[[k.replace('service ',''),f"{r['cases'][k]['weight_lb']:,.0f}",f"{r['cases'][k]['max_vertical_in']:.3f}"] for k in ['service occupied','service storage bands','service full125','service patch1000']],[290,120,122])
p('Occupied = D + 40 psf floor live + 20 psf projected roof live. Storage bands = 125 psf in 36-inch north/east/west strips, 40 psf elsewhere, plus D and roof live. Full125 applies 125 psf everywhere. Patch1000 adds 1,000 lb directly at B2 midspan to the occupied case. Balcony live allowance is 60 psf.')
p('Strength search cases are 1.2D + 1.6 band-load + 0.5 roof-live, and 1.2D + band-load + 1.6 roof-live. These are selected study combinations, not an exhaustive code envelope. Full125 and patch1000 are service sensitivity checks, not fully strength-qualified design cases. The 0.75-inch maximum movement search limit is a study tolerance, not a member-specific code deflection check.')
page();h('Column reactions: perimeter storage case')
if (P/'reaction-plan.png').exists():story.append(Image(str(P/'reaction-plan.png'),width=440,height=355))
a=r['cases']['service storage bands']['columns'];b=r['sensitivity']['without optional S3']['service storage bands']['columns']
table([['Column','With S3, lb','Without S3, lb']]+[[k,f"{v['P_lb']:,.0f}",f"{b[k]['P_lb']:,.0f}"] for k,v in a.items()],[170,180,182])
p('These are service vertical base reactions. S1 contributes only its own 85 lb: including a column in the model does not connect it to the roof. Removing S3 moves S2 from about 5,000 to 12,800 lb. The CSV includes column shears and base moments for every case; footing demand cannot be reduced to axial load alone.')
page();h('Candidate sections from the bounded search')
p('<b>Analytical trial sections only.</b> A500 Grade C square HSS, Fy = 50 ksi. Dimensions are outside size and nominal wall thickness in inches. Catalogue properties are from Atlas Tube. These sections have not passed connection, lateral stability, foundation or full code checks.')
table([['Member family','Trial square HSS']]+[[k,v['name'].replace('HSS','')] for k,v in r['selection'].items()],[270,262])
p('The result is not uniformly thin tubing: T-E and T-W use 6-inch chords, while the transverse T1 uses 5-inch chords. Their stiffness and frame action matter. The very light T-S result depends on the assumed east-west roof spanning direction and must not be generalized to a different roof layout.')
p('All columns were screened as 4 x 4 x 0.188. This does not establish that 4-inch posts are adequate: the first-order base restraint and lateral system remain assumptions, and second-order effects are omitted. W-sections, rectangular HSS, cold-formed members and timber trusses were not optimized in this search.')
page();h('Sensitivity and member-force checks')
table([['Model variation','Storage movement, in','Y lateral movement, in']]+[['Baseline',f"{r['cases']['service storage bands']['max_vertical_in']:.3f}",f"{r['cases']['lateral Y sensitivity']['max_horizontal_in']:.3f}"]]+[[k,f"{v['service storage bands']['max_vertical_in']:.3f}",f"{v['lateral Y sensitivity']['max_horizontal_in']:.3f}"] for k,v in r['sensitivity'].items()],[290,121,121])
p('The lateral runs use an arbitrary 20 psf gross-area pressure for sensitivity only. They are not San Diego design wind pressures. Uplift uses an equally diagnostic 20 psf case. No wind or seismic adequacy conclusion follows from them. Reduced truss stiffness increases movement substantially, showing why real joints cannot be left unspecified.')
rows=[['Group','Compression, kip','Bending, kip-ft','Max screen ratio']]
for g in ['T-S','T1','T-W','T-E','T-N','B2','B3','T-SO']:
 vals=[r['cases'][k]['groups'][g] for k in ['strength floor','strength roof']]
 rows.append([g,f"{max(v['Ncomp'] for v in vals)/1000:.2f}",f"{max(v['M'] for v in vals)/12000:.2f}",f"{max(v['ratio'] for v in vals):.3f}"])
table(rows,[100,145,145,142])
p('Values are independent maxima anywhere in each group, not simultaneous forces on a single member. Full axial tension, shear, torsion and case-by-case envelopes are in member-group-demands.csv. The ratio is an internal screening metric, not an AISC certification.')
p('Screening uses the AISC E3 column curve, elastic bending yield, a conservative linear axial/biaxial interaction and an approximate shear/torsion screen. K = 1 and chord brace spacing at most 72 inches are assumed. Those brace points must be provided and designed. End-connection local yielding, punching, welds, bolts, gussets and tube-face flexibility are not checked.')
page();h('The 1,000 lb item: floor framing')
p('Simple joist check: span 115.25 inches, spacing 16 inches, 9 psf dead plus 40 psf live, with the entire 1,000 lb placed at midspan of one joist. This is deliberately localized; load spreading through the plywood has not been established.')
table([['Member','Live movement, in','Bending demand']]+[[v['member'],f"{v['live_deflection_in']:.3f}",f"{v.get('required_bending_stress_psi',v.get('elastic_stress_psi')):,.0f} psi"] for v in sec['floor_joist_1000lb_on_one_member_plus_uniform']],[270,115,147])
p('L/360 here is 0.320 inch. A single 2x8 fails that movement screen. A 2x10 meets this one deflection screen but still needs a species/grade and adjusted bending capacity of about 1,770 psi. HSS 4x4x0.188 also meets this isolated movement screen, at about 9.42 lb/ft versus an assumed 3.37 lb/ft for the wood 2x10. Neither is a complete floor design.')
p('For low weight, the present comparison favors investigating wood or engineered-wood joists with a deliberately reinforced storage pad. Steel cold-formed joists may be competitive but need a separate local/distortional-buckling design. The plywood must be checked for the actual contact footprint; placing a heavy item above a primary support is much more useful than averaging it over the loft.')
h('Secondary roof framing')
p('An isolated square-HSS purlin screen at 4 ft spacing over 18 ft 8-1/4 in gives HSS 5x5x0.25 as the lightest listed candidate meeting the selected L/240 and elastic stress screens, at 15.62 lb/ft. This is already roughly 3.9 psf on projected area. A lighter roof therefore needs efficient purlin profiles or a shorter effective span; thin cladding alone does not make the roof light. Cold-formed Z/C purlins and their restraint details were not designed here.')
page();h('Reproducibility, limits and engineering handoff')
p('Python model: 438 nodes and 541 frame elements; six degrees of freedom per node, Euler-Bernoulli bending, axial stiffness and Saint-Venant torsion. E = 29,000 ksi. Tests verify cantilever bending, axial extension, torsion and simply supported point-load bending. Each run checks force and moment equilibrium and free-degree residuals. The shear-seat option uses statically condensed end releases.')
p('Run frame_solver tests, then study.py for the baseline, then extra_checks.py. The two variant directories retain their own results and analytical geometries. Use TRUSS_OPTION=triangulated for the triangulated variant; add SHEAR_SEATS=1 for the shear-seat variant. Frozen source geometry is included in inputs/. make_report.py uses saved results and ReportLab; plot_report.py uses Matplotlib. NumPy and SciPy are required for analysis.')
p('The section search selects from a finite square-HSS catalogue, updates self-weight after changes, and downsizes member families while meeting selected strength and movement screens. It is a local search with grouped sections, not a mathematical minimum. Model equilibrium does not verify that the assumed physical load path or joints can be built.')
p('Before final sizing, a California licensed structural engineer needs to establish occupancy and storage design loads; site wind/exposure and seismic parameters; lateral system and diaphragm forces; second-order stability; actual joint stiffness, gussets and welds; beam seats and eccentricities; member-specific deflection and floor vibration; roof collectors and purlins; snow/rain/ponding and uplift cases; column baseplates/anchors; and footing soil, bearing and overturning capacity. The existing wall/slab reserve has intentionally not been presumed.')
h('Primary references')
sources=[('San Diego current codes','https://www.sandiego.gov/development-services/codes-regulations'),('San Diego residential addition/remodel guidance','https://www.sandiego.gov/development-services/forms-publications/information-bulletins/140'),('Atlas A500 square HSS catalogue','https://www.atlastube.com/wp-content/uploads/2018/04/A500-Square-Current.pdf'),('Canadian Solar module dimensions and weight','https://www.canadiansolar.com/wp-content/uploads/sites/3/2026/01/CS-Datasheet-TOPHiKu6_All-Black_CS6.1-54TM-H_v1.4C25_F23_D2_TX.pdf'),('Metl-Span panel weight reference','https://metlspan.com/wp-content/uploads/2022/11/PSF-Panel-Weights_2019.pdf'),('AISC 360-16 with revisions: E3 formula reference','https://www.aisc.org/globalassets/aisc/publications/standards/a360-16w-rev-june-2019.pdf'),('Steel Tube Institute section and availability resources','https://steeltubeinstitute.org/hss-tools/')]
for title,url in sources:p(f'<link href="{url}" color="#126080">{title}</link>')
p('Sources inform this screen; they do not establish compliance with the currently adopted 2025 California codes. The 40/125 psf scenarios are explicit study assumptions pending use classification, and manufacturer weights do not certify the proposed integrated solar roof assembly.')
SimpleDocTemplate(str(P/'garage-structural-review.pdf'),pagesize=(612,792),rightMargin=40,leftMargin=40,topMargin=38,bottomMargin=42).build(story,onFirstPage=footer,onLaterPages=footer)
(P/'README.md').write_text('\n'.join(md))
print('Created PDF and README')
